
// This file has been generated by the GUI designer. Do not modify.
namespace FirefoxCleaner
{
	public partial class MainWindow
	{
		private global::Gtk.Alignment alignment1;
		private global::Gtk.Fixed MainPanel;
		private global::Gtk.CheckButton InetHistory;
		private global::Gtk.CheckButton InetCache;
		private global::Gtk.CheckButton Cookies;
		private global::Gtk.CheckButton AdblockBackups;
		private global::Gtk.CheckButton BookmarkBackups;
		private global::Gtk.CheckButton CrashReports;
		private global::Gtk.CheckButton DownloadHistory;
		private global::Gtk.CheckButton FFExtLog;
		private global::Gtk.CheckButton FFCorruptSQL;
		private global::Gtk.CheckButton FFLogs;
		private global::Gtk.CheckButton FFMinidumps;
		private global::Gtk.CheckButton FFStartupCache;
		private global::Gtk.CheckButton FFTelemetry;
		private global::Gtk.CheckButton FFurlclassifier3;
		private global::Gtk.CheckButton LockFiles;
		private global::Gtk.CheckButton FFwebappsstore;
		private global::Gtk.CheckButton FFTestPilotErrorLogs;
		private global::Gtk.CheckButton FFUpdateLogs;
		private global::Gtk.CheckButton MaintenServLogs;
		private global::Gtk.CheckButton FlashGot;
		private global::Gtk.CheckButton StylishSyncBackups;
		private global::Gtk.CheckButton RecovFileFragments;
		private global::Gtk.CheckButton Thumbnails;
		private global::Gtk.CheckButton MZUpdates;
		private global::Gtk.CheckButton SyncLogs;
		private global::Gtk.CheckButton CompactDB;
		private global::Gtk.CheckButton DumpFiles;
		private global::Gtk.Button UninstallFirefoxBtn;
		private global::Gtk.Button ClearBtn;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget FirefoxCleaner.MainWindow
			this.WidthRequest = 525;
			this.HeightRequest = 288;
			this.Name = "FirefoxCleaner.MainWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("FirefoxCleaner");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.Resizable = false;
			this.Gravity = ((global::Gdk.Gravity)(5));
			// Container child FirefoxCleaner.MainWindow.Gtk.Container+ContainerChild
			this.alignment1 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment1.Name = "alignment1";
			this.alignment1.BorderWidth = ((uint)(3));
			// Container child alignment1.Gtk.Container+ContainerChild
			this.MainPanel = new global::Gtk.Fixed ();
			this.MainPanel.Name = "MainPanel";
			this.MainPanel.HasWindow = false;
			// Container child MainPanel.Gtk.Fixed+FixedChild
			this.InetHistory = new global::Gtk.CheckButton ();
			this.InetHistory.Name = "InetHistory";
			this.InetHistory.Label = global::Mono.Unix.Catalog.GetString ("Internet History");
			this.InetHistory.DrawIndicator = true;
			this.InetHistory.UseUnderline = true;
			this.InetHistory.FocusOnClick = false;
			this.MainPanel.Add (this.InetHistory);
			global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.MainPanel [this.InetHistory]));
			w1.X = 4;
			w1.Y = 4;
			// Container child MainPanel.Gtk.Fixed+FixedChild
			this.InetCache = new global::Gtk.CheckButton ();
			this.InetCache.Name = "InetCache";
			this.InetCache.Label = global::Mono.Unix.Catalog.GetString ("Internet Cache");
			this.InetCache.DrawIndicator = true;
			this.InetCache.UseUnderline = true;
			this.InetCache.FocusOnClick = false;
			this.MainPanel.Add (this.InetCache);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.MainPanel [this.InetCache]));
			w2.X = 4;
			w2.Y = 24;
			// Container child MainPanel.Gtk.Fixed+FixedChild
			this.Cookies = new global::Gtk.CheckButton ();
			this.Cookies.Name = "Cookies";
			this.Cookies.Label = global::Mono.Unix.Catalog.GetString ("Cookies");
			this.Cookies.DrawIndicator = true;
			this.Cookies.UseUnderline = true;
			this.Cookies.FocusOnClick = false;
			this.MainPanel.Add (this.Cookies);
			global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.MainPanel [this.Cookies]));
			w3.X = 4;
			w3.Y = 44;
			// Container child MainPanel.Gtk.Fixed+FixedChild
			this.AdblockBackups = new global::Gtk.CheckButton ();
			this.AdblockBackups.Name = "AdblockBackups";
			this.AdblockBackups.Label = global::Mono.Unix.Catalog.GetString ("Adblock Backups");
			this.AdblockBackups.DrawIndicator = true;
			this.AdblockBackups.UseUnderline = true;
			this.AdblockBackups.FocusOnClick = false;
			this.MainPanel.Add (this.AdblockBackups);
			global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.MainPanel [this.AdblockBackups]));
			w4.X = 4;
			w4.Y = 64;
			// Container child MainPanel.Gtk.Fixed+FixedChild
			this.BookmarkBackups = new global::Gtk.CheckButton ();
			this.BookmarkBackups.Name = "BookmarkBackups";
			this.BookmarkBackups.Label = global::Mono.Unix.Catalog.GetString ("Bookmark Backups");
			this.BookmarkBackups.DrawIndicator = true;
			this.BookmarkBackups.UseUnderline = true;
			this.BookmarkBackups.FocusOnClick = false;
			this.MainPanel.Add (this.BookmarkBackups);
			global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.MainPanel [this.BookmarkBackups]));
			w5.X = 4;
			w5.Y = 84;
			// Container child MainPanel.Gtk.Fixed+FixedChild
			this.CrashReports = new global::Gtk.CheckButton ();
			this.CrashReports.Name = "CrashReports";
			this.CrashReports.Label = global::Mono.Unix.Catalog.GetString ("Crash Reports");
			this.CrashReports.DrawIndicator = true;
			this.CrashReports.UseUnderline = true;
			this.CrashReports.FocusOnClick = false;
			this.MainPanel.Add (this.CrashReports);
			global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.MainPanel [this.CrashReports]));
			w6.X = 4;
			w6.Y = 104;
			// Container child MainPanel.Gtk.Fixed+FixedChild
			this.DownloadHistory = new global::Gtk.CheckButton ();
			this.DownloadHistory.Name = "DownloadHistory";
			this.DownloadHistory.Label = global::Mono.Unix.Catalog.GetString ("Download History");
			this.DownloadHistory.DrawIndicator = true;
			this.DownloadHistory.UseUnderline = true;
			this.DownloadHistory.FocusOnClick = false;
			this.MainPanel.Add (this.DownloadHistory);
			global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.MainPanel [this.DownloadHistory]));
			w7.X = 4;
			w7.Y = 124;
			// Container child MainPanel.Gtk.Fixed+FixedChild
			this.FFExtLog = new global::Gtk.CheckButton ();
			this.FFExtLog.Name = "FFExtLog";
			this.FFExtLog.Label = global::Mono.Unix.Catalog.GetString ("Firefox Extensions Log");
			this.FFExtLog.DrawIndicator = true;
			this.FFExtLog.UseUnderline = true;
			this.FFExtLog.FocusOnClick = false;
			this.MainPanel.Add (this.FFExtLog);
			global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.MainPanel [this.FFExtLog]));
			w8.X = 4;
			w8.Y = 184;
			// Container child MainPanel.Gtk.Fixed+FixedChild
			this.FFCorruptSQL = new global::Gtk.CheckButton ();
			this.FFCorruptSQL.Name = "FFCorruptSQL";
			this.FFCorruptSQL.Label = global::Mono.Unix.Catalog.GetString ("Firefox Corrupt SQLites");
			this.FFCorruptSQL.DrawIndicator = true;
			this.FFCorruptSQL.UseUnderline = true;
			this.FFCorruptSQL.FocusOnClick = false;
			this.MainPanel.Add (this.FFCorruptSQL);
			global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.MainPanel [this.FFCorruptSQL]));
			w9.X = 4;
			w9.Y = 164;
			// Container child MainPanel.Gtk.Fixed+FixedChild
			this.FFLogs = new global::Gtk.CheckButton ();
			this.FFLogs.Name = "FFLogs";
			this.FFLogs.Label = global::Mono.Unix.Catalog.GetString ("Firefox Logs");
			this.FFLogs.DrawIndicator = true;
			this.FFLogs.UseUnderline = true;
			this.FFLogs.FocusOnClick = false;
			this.MainPanel.Add (this.FFLogs);
			global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.MainPanel [this.FFLogs]));
			w10.X = 4;
			w10.Y = 204;
			// Container child MainPanel.Gtk.Fixed+FixedChild
			this.FFMinidumps = new global::Gtk.CheckButton ();
			this.FFMinidumps.Name = "FFMinidumps";
			this.FFMinidumps.Label = global::Mono.Unix.Catalog.GetString ("Firefox Minidumps");
			this.FFMinidumps.DrawIndicator = true;
			this.FFMinidumps.UseUnderline = true;
			this.FFMinidumps.FocusOnClick = false;
			this.MainPanel.Add (this.FFMinidumps);
			global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.MainPanel [this.FFMinidumps]));
			w11.X = 4;
			w11.Y = 224;
			// Container child MainPanel.Gtk.Fixed+FixedChild
			this.FFStartupCache = new global::Gtk.CheckButton ();
			this.FFStartupCache.Name = "FFStartupCache";
			this.FFStartupCache.Label = global::Mono.Unix.Catalog.GetString ("Firefox Startup Cache");
			this.FFStartupCache.DrawIndicator = true;
			this.FFStartupCache.UseUnderline = true;
			this.FFStartupCache.FocusOnClick = false;
			this.MainPanel.Add (this.FFStartupCache);
			global::Gtk.Fixed.FixedChild w12 = ((global::Gtk.Fixed.FixedChild)(this.MainPanel [this.FFStartupCache]));
			w12.X = 190;
			w12.Y = 4;
			// Container child MainPanel.Gtk.Fixed+FixedChild
			this.FFTelemetry = new global::Gtk.CheckButton ();
			this.FFTelemetry.Name = "FFTelemetry";
			this.FFTelemetry.Label = global::Mono.Unix.Catalog.GetString ("Firefox Telemetry");
			this.FFTelemetry.DrawIndicator = true;
			this.FFTelemetry.UseUnderline = true;
			this.FFTelemetry.FocusOnClick = false;
			this.MainPanel.Add (this.FFTelemetry);
			global::Gtk.Fixed.FixedChild w13 = ((global::Gtk.Fixed.FixedChild)(this.MainPanel [this.FFTelemetry]));
			w13.X = 190;
			w13.Y = 24;
			// Container child MainPanel.Gtk.Fixed+FixedChild
			this.FFurlclassifier3 = new global::Gtk.CheckButton ();
			this.FFurlclassifier3.Name = "FFurlclassifier3";
			this.FFurlclassifier3.Label = global::Mono.Unix.Catalog.GetString ("Firefox urlclassifier3.sqlite");
			this.FFurlclassifier3.DrawIndicator = true;
			this.FFurlclassifier3.UseUnderline = true;
			this.FFurlclassifier3.FocusOnClick = false;
			this.MainPanel.Add (this.FFurlclassifier3);
			global::Gtk.Fixed.FixedChild w14 = ((global::Gtk.Fixed.FixedChild)(this.MainPanel [this.FFurlclassifier3]));
			w14.X = 190;
			w14.Y = 84;
			// Container child MainPanel.Gtk.Fixed+FixedChild
			this.LockFiles = new global::Gtk.CheckButton ();
			this.LockFiles.Name = "LockFiles";
			this.LockFiles.Label = global::Mono.Unix.Catalog.GetString ("Lock Files");
			this.LockFiles.DrawIndicator = true;
			this.LockFiles.UseUnderline = true;
			this.LockFiles.FocusOnClick = false;
			this.MainPanel.Add (this.LockFiles);
			global::Gtk.Fixed.FixedChild w15 = ((global::Gtk.Fixed.FixedChild)(this.MainPanel [this.LockFiles]));
			w15.X = 190;
			w15.Y = 144;
			// Container child MainPanel.Gtk.Fixed+FixedChild
			this.FFwebappsstore = new global::Gtk.CheckButton ();
			this.FFwebappsstore.Name = "FFwebappsstore";
			this.FFwebappsstore.Label = global::Mono.Unix.Catalog.GetString ("Firefox webappsstore.sqlite");
			this.FFwebappsstore.DrawIndicator = true;
			this.FFwebappsstore.UseUnderline = true;
			this.FFwebappsstore.FocusOnClick = false;
			this.MainPanel.Add (this.FFwebappsstore);
			global::Gtk.Fixed.FixedChild w16 = ((global::Gtk.Fixed.FixedChild)(this.MainPanel [this.FFwebappsstore]));
			w16.X = 190;
			w16.Y = 104;
			// Container child MainPanel.Gtk.Fixed+FixedChild
			this.FFTestPilotErrorLogs = new global::Gtk.CheckButton ();
			this.FFTestPilotErrorLogs.Name = "FFTestPilotErrorLogs";
			this.FFTestPilotErrorLogs.Label = global::Mono.Unix.Catalog.GetString ("Firefox TestPilot Error Logs");
			this.FFTestPilotErrorLogs.DrawIndicator = true;
			this.FFTestPilotErrorLogs.UseUnderline = true;
			this.FFTestPilotErrorLogs.FocusOnClick = false;
			this.MainPanel.Add (this.FFTestPilotErrorLogs);
			global::Gtk.Fixed.FixedChild w17 = ((global::Gtk.Fixed.FixedChild)(this.MainPanel [this.FFTestPilotErrorLogs]));
			w17.X = 190;
			w17.Y = 44;
			// Container child MainPanel.Gtk.Fixed+FixedChild
			this.FFUpdateLogs = new global::Gtk.CheckButton ();
			this.FFUpdateLogs.Name = "FFUpdateLogs";
			this.FFUpdateLogs.Label = global::Mono.Unix.Catalog.GetString ("Firefox Update Logs");
			this.FFUpdateLogs.DrawIndicator = true;
			this.FFUpdateLogs.UseUnderline = true;
			this.FFUpdateLogs.FocusOnClick = false;
			this.MainPanel.Add (this.FFUpdateLogs);
			global::Gtk.Fixed.FixedChild w18 = ((global::Gtk.Fixed.FixedChild)(this.MainPanel [this.FFUpdateLogs]));
			w18.X = 190;
			w18.Y = 64;
			// Container child MainPanel.Gtk.Fixed+FixedChild
			this.MaintenServLogs = new global::Gtk.CheckButton ();
			this.MaintenServLogs.Name = "MaintenServLogs";
			this.MaintenServLogs.Label = global::Mono.Unix.Catalog.GetString ("Maintenance Service Logs");
			this.MaintenServLogs.DrawIndicator = true;
			this.MaintenServLogs.UseUnderline = true;
			this.MaintenServLogs.FocusOnClick = false;
			this.MainPanel.Add (this.MaintenServLogs);
			global::Gtk.Fixed.FixedChild w19 = ((global::Gtk.Fixed.FixedChild)(this.MainPanel [this.MaintenServLogs]));
			w19.X = 190;
			w19.Y = 164;
			// Container child MainPanel.Gtk.Fixed+FixedChild
			this.FlashGot = new global::Gtk.CheckButton ();
			this.FlashGot.Name = "FlashGot";
			this.FlashGot.Label = global::Mono.Unix.Catalog.GetString ("FlashGot");
			this.FlashGot.DrawIndicator = true;
			this.FlashGot.UseUnderline = true;
			this.FlashGot.FocusOnClick = false;
			this.MainPanel.Add (this.FlashGot);
			global::Gtk.Fixed.FixedChild w20 = ((global::Gtk.Fixed.FixedChild)(this.MainPanel [this.FlashGot]));
			w20.X = 190;
			w20.Y = 124;
			// Container child MainPanel.Gtk.Fixed+FixedChild
			this.StylishSyncBackups = new global::Gtk.CheckButton ();
			this.StylishSyncBackups.Name = "StylishSyncBackups";
			this.StylishSyncBackups.Label = global::Mono.Unix.Catalog.GetString ("Stylish Sync Backups");
			this.StylishSyncBackups.DrawIndicator = true;
			this.StylishSyncBackups.UseUnderline = true;
			this.StylishSyncBackups.FocusOnClick = false;
			this.MainPanel.Add (this.StylishSyncBackups);
			global::Gtk.Fixed.FixedChild w21 = ((global::Gtk.Fixed.FixedChild)(this.MainPanel [this.StylishSyncBackups]));
			w21.X = 190;
			w21.Y = 224;
			// Container child MainPanel.Gtk.Fixed+FixedChild
			this.RecovFileFragments = new global::Gtk.CheckButton ();
			this.RecovFileFragments.Name = "RecovFileFragments";
			this.RecovFileFragments.Label = global::Mono.Unix.Catalog.GetString ("Recovered File Fragments");
			this.RecovFileFragments.DrawIndicator = true;
			this.RecovFileFragments.UseUnderline = true;
			this.RecovFileFragments.FocusOnClick = false;
			this.MainPanel.Add (this.RecovFileFragments);
			global::Gtk.Fixed.FixedChild w22 = ((global::Gtk.Fixed.FixedChild)(this.MainPanel [this.RecovFileFragments]));
			w22.X = 190;
			w22.Y = 204;
			// Container child MainPanel.Gtk.Fixed+FixedChild
			this.Thumbnails = new global::Gtk.CheckButton ();
			this.Thumbnails.Name = "Thumbnails";
			this.Thumbnails.Label = global::Mono.Unix.Catalog.GetString ("Thumbnails");
			this.Thumbnails.DrawIndicator = true;
			this.Thumbnails.UseUnderline = true;
			this.Thumbnails.FocusOnClick = false;
			this.MainPanel.Add (this.Thumbnails);
			global::Gtk.Fixed.FixedChild w23 = ((global::Gtk.Fixed.FixedChild)(this.MainPanel [this.Thumbnails]));
			w23.X = 410;
			w23.Y = 24;
			// Container child MainPanel.Gtk.Fixed+FixedChild
			this.MZUpdates = new global::Gtk.CheckButton ();
			this.MZUpdates.Name = "MZUpdates";
			this.MZUpdates.Label = global::Mono.Unix.Catalog.GetString ("Mozilla Updates");
			this.MZUpdates.DrawIndicator = true;
			this.MZUpdates.UseUnderline = true;
			this.MZUpdates.FocusOnClick = false;
			this.MainPanel.Add (this.MZUpdates);
			global::Gtk.Fixed.FixedChild w24 = ((global::Gtk.Fixed.FixedChild)(this.MainPanel [this.MZUpdates]));
			w24.X = 190;
			w24.Y = 184;
			// Container child MainPanel.Gtk.Fixed+FixedChild
			this.SyncLogs = new global::Gtk.CheckButton ();
			this.SyncLogs.Name = "SyncLogs";
			this.SyncLogs.Label = global::Mono.Unix.Catalog.GetString ("Sync Logs");
			this.SyncLogs.DrawIndicator = true;
			this.SyncLogs.UseUnderline = true;
			this.SyncLogs.FocusOnClick = false;
			this.MainPanel.Add (this.SyncLogs);
			global::Gtk.Fixed.FixedChild w25 = ((global::Gtk.Fixed.FixedChild)(this.MainPanel [this.SyncLogs]));
			w25.X = 410;
			w25.Y = 4;
			// Container child MainPanel.Gtk.Fixed+FixedChild
			this.CompactDB = new global::Gtk.CheckButton ();
			this.CompactDB.Name = "CompactDB";
			this.CompactDB.Label = global::Mono.Unix.Catalog.GetString ("Compact Databases");
			this.CompactDB.DrawIndicator = true;
			this.CompactDB.UseUnderline = true;
			this.CompactDB.FocusOnClick = false;
			this.MainPanel.Add (this.CompactDB);
			global::Gtk.Fixed.FixedChild w26 = ((global::Gtk.Fixed.FixedChild)(this.MainPanel [this.CompactDB]));
			w26.X = 4;
			w26.Y = 144;
			// Container child MainPanel.Gtk.Fixed+FixedChild
			this.DumpFiles = new global::Gtk.CheckButton ();
			this.DumpFiles.Name = "DumpFiles";
			this.DumpFiles.Label = global::Mono.Unix.Catalog.GetString ("Dump Files");
			this.DumpFiles.DrawIndicator = true;
			this.DumpFiles.UseUnderline = true;
			this.DumpFiles.FocusOnClick = false;
			this.MainPanel.Add (this.DumpFiles);
			global::Gtk.Fixed.FixedChild w27 = ((global::Gtk.Fixed.FixedChild)(this.MainPanel [this.DumpFiles]));
			w27.X = 410;
			w27.Y = 44;
			// Container child MainPanel.Gtk.Fixed+FixedChild
			this.UninstallFirefoxBtn = new global::Gtk.Button ();
			this.UninstallFirefoxBtn.WidthRequest = 155;
			this.UninstallFirefoxBtn.CanFocus = true;
			this.UninstallFirefoxBtn.Name = "UninstallFirefoxBtn";
			this.UninstallFirefoxBtn.UseUnderline = true;
			this.UninstallFirefoxBtn.Label = global::Mono.Unix.Catalog.GetString ("Uninstall Firefox");
			this.MainPanel.Add (this.UninstallFirefoxBtn);
			global::Gtk.Fixed.FixedChild w28 = ((global::Gtk.Fixed.FixedChild)(this.MainPanel [this.UninstallFirefoxBtn]));
			w28.X = 4;
			w28.Y = 249;
			// Container child MainPanel.Gtk.Fixed+FixedChild
			this.ClearBtn = new global::Gtk.Button ();
			this.ClearBtn.WidthRequest = 87;
			this.ClearBtn.CanFocus = true;
			this.ClearBtn.Name = "ClearBtn";
			this.ClearBtn.UseUnderline = true;
			this.ClearBtn.Label = global::Mono.Unix.Catalog.GetString ("Clear");
			this.MainPanel.Add (this.ClearBtn);
			global::Gtk.Fixed.FixedChild w29 = ((global::Gtk.Fixed.FixedChild)(this.MainPanel [this.ClearBtn]));
			w29.X = 428;
			w29.Y = 249;
			this.alignment1.Add (this.MainPanel);
			this.Add (this.alignment1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 543;
			this.DefaultHeight = 323;
			this.Show ();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
			this.InetHistory.Clicked += new global::System.EventHandler (this.OnInetHistoryClicked);
			this.InetCache.Clicked += new global::System.EventHandler (this.OnInetCacheClicked);
			this.Cookies.Clicked += new global::System.EventHandler (this.OnCookiesClicked);
			this.AdblockBackups.Clicked += new global::System.EventHandler (this.OnAdblockBackupsClicked);
			this.BookmarkBackups.Clicked += new global::System.EventHandler (this.OnBookmarkBackupsClicked);
			this.CrashReports.Clicked += new global::System.EventHandler (this.OnCrashReportsClicked);
			this.DownloadHistory.Clicked += new global::System.EventHandler (this.OnDownloadHistoryClicked);
			this.FFExtLog.Clicked += new global::System.EventHandler (this.OnFFExtLogClicked);
			this.FFCorruptSQL.Clicked += new global::System.EventHandler (this.OnFFCorruptSQLClicked);
			this.FFLogs.Clicked += new global::System.EventHandler (this.OnFFLogsClicked);
			this.FFMinidumps.Clicked += new global::System.EventHandler (this.OnFFMinidumpsClicked);
			this.FFStartupCache.Clicked += new global::System.EventHandler (this.OnFFStartupCacheClicked);
			this.FFTelemetry.Clicked += new global::System.EventHandler (this.OnFFTelemetryClicked);
			this.FFurlclassifier3.Clicked += new global::System.EventHandler (this.OnFFurlclassifier3Clicked);
			this.LockFiles.Clicked += new global::System.EventHandler (this.OnLockFilesClicked);
			this.FFwebappsstore.Clicked += new global::System.EventHandler (this.OnFFwebappsstoreClicked);
			this.FFTestPilotErrorLogs.Clicked += new global::System.EventHandler (this.OnFFTestPilotErrorLogsClicked);
			this.FFUpdateLogs.Clicked += new global::System.EventHandler (this.OnFFUpdateLogsClicked);
			this.MaintenServLogs.Clicked += new global::System.EventHandler (this.OnMaintenServLogsClicked);
			this.FlashGot.Clicked += new global::System.EventHandler (this.OnFlashGotClicked);
			this.StylishSyncBackups.Clicked += new global::System.EventHandler (this.OnStylishSyncBackupsClicked);
			this.RecovFileFragments.Clicked += new global::System.EventHandler (this.OnRecovFileFragmentsClicked);
			this.Thumbnails.Clicked += new global::System.EventHandler (this.OnThumbnailsClicked);
			this.MZUpdates.Clicked += new global::System.EventHandler (this.OnMZUpdatesClicked);
			this.SyncLogs.Clicked += new global::System.EventHandler (this.OnSyncLogsClicked);
			this.CompactDB.Clicked += new global::System.EventHandler (this.OnCompactDBClicked);
			this.DumpFiles.Clicked += new global::System.EventHandler (this.OnDumpFilesClicked);
			this.UninstallFirefoxBtn.Clicked += new global::System.EventHandler (this.OnUninstallFirefoxBtnClicked);
			this.ClearBtn.Clicked += new global::System.EventHandler (this.OnClearBtnClicked);
		}
	}
}
